ingress:
  alb: true

persistence:
  ebs: true

pulsar:
  global:
    storageClass: "ebs-sc"

  zookeeper:
    persistance:
      storageClass: "ebs-sc"
    volumes:
      data:
        storageClassname: "ebs-sc"

  bookkeeper:
    volumes:
      journal:
        storageClassName: "ebs-sc"
      ledgers:
        storageClassName: "ebs-sc"

postgresql:
  primary:
    resources:
      limits:
        cpu: 1
    persistence:
      storageClassName: "ebs-sc"
