services:
  postgres:
    image: postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth

    volumes:
      - postgres_data:/var/lib/postgresql/data

  pulsar:
    image: apachepulsar/pulsar:latest
    command: >
      sh -c "python3 /pulsar/bin/apply-config-from-env.py /pulsar/conf/standalone.conf &&
             /pulsar/bin/pulsar standalone"
    environment:
      - PULSAR_PREFIX_advertisedAddress=localhost
    ports:
      - 6650:6650

volumes:
  postgres_data:
