{{- if .Values.jobs.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobs
  labels:
    app: jobs
spec:
  replicas: {{ .Values.jobs.replicas | int }}
  selector:
    matchLabels:
      app: jobs
  template:
    metadata:
      labels:
        app: jobs
    spec:
      initContainers:
        - name: prisma-migrate
          image: {{ .Values.jobs.image | quote }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy | quote }}
          command: ["sh", "-c"]
          args:
            - |
              npx prisma migrate deploy
          env:
            {{- include "common.env" . | nindent 12 }}
            - name: DATABASE_URL
              value: postgresql://postgres:postgres@{{ .Release.Name }}-postgresql.postgresql.svc.cluster.local:5432/jobs
      containers:
        - name: jobs
          image: {{ .Values.jobs.image | quote }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy | quote }}
          volumeMounts:
            - name: uploads-volume
              mountPath: /app/apps/jobs/uploads
          ports:
            - containerPort: {{ .Values.jobs.port.http | int }}
            - containerPort: {{ .Values.jobs.port.grpc | int }}
          env:
            {{- include "common.env" . | nindent 12 }}
            - name: AUTH_SERVICE_GRPC_URL
              value: "auth-grpc.jobber.svc.cluster.local:{{ .Values.auth.port.grpc }}"
            - name: PORT
              value: "{{ .Values.jobs.port.http }}"
            - name: JOBS_SERVICE_GRPC_URL
              value: "0.0.0.0:{{ .Values.jobs.port.grpc }}"
            - name: DATABASE_URL
              value: postgresql://postgres:postgres@{{ .Release.Name }}-postgresql.postgresql.svc.cluster.local:5432/jobs
            - name: JWT_SECRET
              value: {{ .Values.auth.jwt.secret | quote }}
      volumes:
        - name: uploads-volume
          persistentVolumeClaim:
            claimName: uploads-pvc

{{- end }}
